### ISSUE TITLE
Implement logging util for us to redirect debug messages to file

### ISSUE THREAD

**Issue by twstagg** [oceancabbage/RimSort#15]
- This util should have at a minimum 2 log levels that are configurable in global settings:
    - Standard
    - Debug
- Ideally will route useful junk to a file, print error level msgs to stdout

**Comment by N3X15** [comment]
The built-in logging system works well for this, and can be fed configuration from a file or CLI options.

**Comment by twstagg** [comment]
Looks completed to me!
