### ISSUE TITLE
Implement minor QoL/usability suggestions

### ISSUE THREAD

**Issue by largemoron** [oceancabbage/RimSort#32]
When building modpacks in RimPy, I found it a lot more convenient to navigate and build mod lists with the keyboard and arrow keys, so here are some QOL/usability things that would be handy:

- [x] (not keyboard but) Double clicking a mod to move it between Inactive and Active lists. Right now only clicking and dragging can do that.
- [x] With a mod in the Inactive list selected, pressing Enter to add it to the Active list and vice versa. 
- [x] Using the left and right arrow keys to move the cursor from the Inactive list to the Active list. Accidentally hit enter to add a mod? Just arrow over and press Enter again to remove it.
- [x] A RMB context-menu option to open the local directory for the selected mod. This would be handy for quickly accessing a mod's files.
- [x] A RMB context-menu option to open the workshop page for the selected mod.
- [x] Graphical option(s) to set the specific filter you are searching with (equivalent to RimPy drop-down menu to select the data you are factoring (name, author, package id, etc)
- [x]  An additional search bar filter option that greys out non-matching results instead of hiding them entirely. (I believe Rimpy has this feature (the open/closed eye icon) and it's real handy. This would allow one to search for and easily locate a specific mod without disrupting the entire mod list view.)
- [x] Implement ability for UI to scale based on window size
- [x] [6:48 AM]Owlchemist: feature request: as of rimworld 1.4, if you go into the in-game mod manager, it can show you the mod version (if the about.xml defines it). That could be nice for the rimsort interface to show
- [x]  Double click support to move items between columns.
- [x] Make Refresh icon blink or glow if any changes to game/mods files
- [x] Make Save icon blink or glow if any changes in active mods list

**Comment by largemoron** [comment]
- [ ]  An additional search bar filter option that greys out non-matching results instead of hiding them entirely.

I believe Rimpy has this feature and it's real handy. This would allow one to search for and easily locate a specific mod without disrupting the entire mod list view.

**Comment by twstagg** [comment]
> * [ ]   An additional search bar filter option that greys out non-matching results instead of hiding them entirely.
> 
> 
> I believe Rimpy has this feature (the open/closed eye icon) and it's real handy. This would allow one to search for and easily locate a specific mod without disrupting the entire mod list view.

xD this is kinda how my original implementation worked...

We will be implementing mode switch for this at some point in the future :)

**Comment by twstagg** [comment]
Comments
@[largemoron](https://github.com/largemoron)
largemoron commented [Feb 21, 2023](https://github.com/oceancabbage/RimSort/issues/34#issue-1594412887)

As said in my other Issue post, I like to navigate the mod lists with the keyboard. In RimPy, as you arrow key around the mod lists, the mod preview pane to the left of the mod lists updates as you arrow over to each new mod. With RimSort, it doesn't change unless you mouse click a new mod.

See this attached video for a visual example.
twstagg reacted with thumbs up emoji

**Comment by twstagg** [comment]
All items completed as of 75d5995
