### ISSUE TITLE
FIXME: Fatal error upon trying to select a mod after unsubscribing on the workshop

### ISSUE THREAD

**Issue by largemoron** [oceancabbage/RimSort#33]
- [x] Create additional check & function for missing Preview.png

Steps to reproduce

WIth RimSort open

- Choose any mod from your list and unsubscribe from it on the workshop
- Wait a bit for steam to decide to remove it from your workshop folder (or delete it yourself)
- Click that now missing mod

Crash log with relevant lines attached
[rs_log.log](https://github.com/oceancabbage/RimSort/files/10799857/rs_log.log)

May as well just paste it here too, save you a step downloading it

[INFO][2023-02-21 20:42:27,797][23983][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 1900
[INFO][2023-02-21 20:42:51,872][23983][view.main_content_panel][mod_list_slot][111] : USER ACTION: clicked on a mod list item: hlx.reinforcedmechanoids
[INFO][2023-02-21 20:42:51,874][23983][sub_view.mod_info_panel][display_mod_info][93] : Starting display mod info for info: {'name': 'Reinforced Mechanoids: Tyrikan-Line', 'author': 'Helixien, Taranchuk, OskarPotocki, Luizi, IcingWithCheeseCake, Sir Van, Reann_Shepard', 'supportedVersions': {'li': '1.3'}, 'url': None, 'packageId': 'hlx.reinforcedmechanoids', 'description': 'An expansion of vanilla Rimworld Mechanoids, adding new threats and gameplay mechanics that perfectly fit into vanilla Rimworld.', 'modDependencies': {'li': {'packageId': 'OskarPotocki.VanillaFactionsExpanded.Core', 'displayName': 'Vanilla Expanded Framework', 'steamWorkshopUrl': 'https://steamcommunity.com/sharedfiles/filedetails/?id=1854607105'}}, 'loadAfter': {'li': ['brrainz.harmony', 'Ludeon.RimWorld', 'Ludeon.RimWorld.Royalty', 'Ludeon.RimWorld.Ideology', 'OskarPotocki.VFE.Mechanoid', 'Mlie.MechanoidPower']}, 'folder': '2798710610', 'path': '/Users/USERNAME/Library/Application Support/Steam/steamapps/workshop/content/294100/2798710610', 'isWorkshop': True, 'dependencies': {'oskarpotocki.vanillafactionsexpanded.core'}, 'loadTheseBefore': {('ludeon.rimworld.royalty', True), ('brrainz.harmony', True), ('oskarpotocki.vfe.mechanoid', True), ('ludeon.rimworld.ideology', True), ('ludeon.rimworld', True)}}
[INFO][2023-02-21 20:42:51,874][23983][sub_view.mod_info_panel][display_mod_info][107] : Mod path exists at: /Users/USERNAME/Library/Application Support/Steam/steamapps/workshop/content/294100/2798710610
[ERROR][2023-02-21 20:42:51,875][23983][__main__][handle_exception][37] : Main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "view/main_content_panel.py", line 112, in mod_list_slot
  File "sub_view/mod_info_panel.py", line 122, in display_mod_info
FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/Library/Application Support/Steam/steamapps/workshop/content/294100/2798710610/About'
[INFO][2023-02-21 20:42:51,877][23983][util.error][show_fatal_error][100] : Showing fatal error box with input: [None], [None], [Traceback (most recent call last):
  File "view/main_content_panel.py", line 112, in mod_list_slot
  File "sub_view/mod_info_panel.py", line 122, in display_mod_info
FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/Library/Application Support/Steam/steamapps/workshop/content/294100/2798710610/About'
]
[INFO][2023-02-21 20:42:51,888][23983][util.error][show_fatal_error][125] : Finished showing fatal error box

**Comment by twstagg** [comment]
Thank you for this.

**Comment by twstagg** [comment]
Fixed in sprint-a1.0.3
