### ISSUE TITLE
Implement mod_info_pane update trigger based on keyboard navigation of mod list(s)

### ISSUE THREAD

**Issue by largemoron** [oceancabbage/RimSort#34]
As said in my other Issue post, I like to navigate the mod lists with the keyboard. In RimPy, as you arrow key around the mod lists, the mod preview pane to the left of the mod lists updates as you arrow over to each new mod.  With RimSort, it doesn't change unless you mouse click a new mod. 

See this attached video for a visual example.

https://user-images.githubusercontent.com/99063144/220515397-d1f7863e-9fc7-4890-8a4e-789d54550c8b.mp4

**Comment by twstagg** [comment]
Very valuable feedback. Please look forward to this in a future update!

**Comment by twstagg** [comment]
This is accounted for in #32
