### ISSUE TITLE
Implement Automatic Redirect to missing dependencies.

### ISSUE THREAD

**Issue by Vexthecollector** [oceancabbage/RimSort#39]
In rimpy, when a dependency is missing, it will simply say it is missing.
Since most rimworld mods implement <steamWorkshopUrl> and <downloadUrl> for their dependencies, it would be a userfriendly feature to implement an automatic redirect to missing dependencies that are not enabled.
Of course this should happen after a clicks on a button like "Download dependencies". For steam it would probably work easier to simply open the steam workshop and let the user press the subscribe button.

For github it might work with the previously talked about "Third Party download" feature.

**Comment by oceancabbage** [comment]
Good point, it would be fairly straightforward to add a couple preliminary features to get this going, e.g. add an option to a mod item's right-click context menu that allows you to open up the link to the mod in the browser. This would be super easy to implement and would pave the way for opening the dependency in the Steam App once we have better Steam integration. Having a button where you could download dependencies would take a bit more work but let's keep this issue open to track the work stream for implementing all features related to downloading/managing dependencies.

**Comment by twstagg** [comment]
Moving to #8
