### ISSUE TITLE
glibc issues on Linux

### ISSUE THREAD

**Issue by joseasoler** [oceancabbage/RimSort#50]
```[147506] Error loading Python lib '/home/kobo/Downloads/rimpy/RimSort/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/kobo/Downloads/rimpy/RimSort/libpython3.10.so.1.0)```

This issue was reported in the main RimWorld discord server by kobo. This problem happens when you have an older glibc version and try to use a binary compiled against a newer glibc version. The binary is not backwards compatible with older glibc versions and fails.

A similar issue happened with RimPy as well. The solution used there was to create a VM using a Linux distribution with a glibc version as ancient as possible, and compiling there.

Another option would be relying on the package manager of the user to install dependencies, which would be linked against the right glibc version. Building RimSort dependencies using static linking so they don't rely on the glibc library of the user would also work.

**Comment by KoboDev** [comment]
Hello, For I am Kobo/Kobayashi.

**Comment by oceancabbage** [comment]
The last option sounds the most optimal to me, though this is a bit out of my league @twstagg I think you might have to take the reins here.

**Comment by twstagg** [comment]
Thanks. After discussion, the solution is to build using older versions of glibc for compatibility purposes. I will continue considering this with releases moving forward. Thanks guys!
