### ISSUE TITLE
FIXME: Rimsort writes .xml twice if you change the name of the modlist when exporting

### ISSUE THREAD

**Issue by Thekiborg** [oceancabbage/RimSort#52]
- [x] Fix `_do_export`

OS: Windows 10 Pro 10.0.19045

1. Export your modlist somewhere
2. In my case, Windows autofills the name with the extension of the file
![image](https://user-images.githubusercontent.com/91976529/227784355-b0ff7c20-8563-4401-a8b4-88f94e55077e.png)
3. If the modlist is exported like this, rimsort will add a second .xml at the end of the files, even with the first one already being in place
![image](https://user-images.githubusercontent.com/91976529/227784403-5bcd3909-208e-4cfb-9731-bd4c18c345b0.png)
4. Changing the file's name and not writing the extension at the end of the name will have similar results
![image](https://user-images.githubusercontent.com/91976529/227784454-85e972ce-0768-4097-a2b6-12ab76538e53.png)
![image](https://user-images.githubusercontent.com/91976529/227784463-c6e870e6-37ce-4827-8956-154ad1861c39.png)

**Comment by twstagg** [comment]
Fixed in [862fb93](https://github.com/oceancabbage/RimSort/pull/46/commits/862fb93e9e61c29db75a88527273a16ef5abc581)
