### ISSUE TITLE
Right click > Delete Mod issues (mac, Alpha v1.0.3-RC2)

### ISSUE THREAD

**Issue by largemoron** [oceancabbage/RimSort#55]
- Using Right click > Delete on a local mod (or red UNKNOWN empty folder) does not move that mod to the Trash, it straight up deletes it.
- MOVED TO SEPARATE ISSUE #60

For the first one, deleted mods should be sent to the Trash for recovery/examination in case the deletion was done by mistake. And just as a general Good Thing to do. It always feels bad when a program deletes something and it's just fucking gone.

Number 2, I don't know, I don't foresee doing bulk deletions beyond removing the 300 or so UNKNOWN folders steam left behind, but it is unexpected behavior. Selecting multiple items and performing an action should apply that action to every selected item.

**Comment by twstagg** [comment]
> * Using Right click > Delete on a local mod (or red UNKNOWN empty folder) does not move that mod to the Trash, it straight up deletes it.

We are going to maintain current behavior at this time. Future options are being considered for those context menu options.

> * Selecting multiple local mods (or UNKNOWN) does not delete every selected mod/folder, only the specific mod you right clicked to bring up the delete menu option.

Moved to #60
