### ISSUE TITLE
NEEDS INVESTIGATED: Fatal Error: Symlink

### ISSUE THREAD

**Issue by kirk33120** [oceancabbage/RimSort#62]
MacOS Silicon

Fatal error during steamcmd setup

Traceback (most recent call last):
File "/Users/UserApplications/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 533, in actions_slot
File "/Users/User/Applications/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 899, in _do_setup_steamcmd
File "/Users/UserApplications/RimSort.app/Contents/MacOS/util/steam/steamcmd/wrapper.py", line 218, in get_steamcmd
FileExistsError: [Errno 17] File exists: '/Users/User/Applications/RimWorldMac.app/Mods' -> '/Users/User/Library/Application Support/RimSort/steam/steamapps/workshop/content/294100'

**Comment by twstagg** [comment]
@kirk33120 This should not be possible, as it should be checking if that path exists or not before prompting to create the symlink for you. Could you please provide the full log?

**Comment by kirk33120** [comment]
sorry for the late reply where do i find the rimsort folder? I was confused by this "You can find the log file (data/RimSort.log) in the RimSort folder."

**Comment by twstagg** [comment]
@kirk33120 no problem my dude. I need to fix that message because the log file location is no longer in the data folder. It is located right next to the executable.

For example:

![image](https://user-images.githubusercontent.com/2766946/235796994-0c326d47-8f84-45bd-93cf-bef5a9815d1f.png)

**Comment by twstagg** [comment]
Unsolvable with current information. Please reopen issue with addt'l information.
