### ISSUE TITLE
Windows 11 MS Defender detects trojan

### ISSUE THREAD

**Issue by sh1ny** [oceancabbage/RimSort#68]
Hello,

I just tried to use RimSort and my MS Defender complains it's a trojan:

https://i.imgur.com/MZ3H66o.png

What can i do ? I don't want to add any exceptions.

**Comment by sh1ny** [comment]
It also gets flagged on virustotal:

https://www.virustotal.com/gui/file/ebb1a3ebeb1da9011c19a59b958b219607cee2843a0c59a2193493e784beb8fc/detection

**Comment by twstagg** [comment]
> Hello,
> 
> I just tried to use RimSort and my MS Defender complains it's a trojan:
> 
> https://i.imgur.com/MZ3H66o.png
> 
> What can i do ? I don't want to add any exceptions.

Please add an exception in your AV for RimSort if you are having issues. It is a false positive.

Eventually, our builds will be released in such a way that this is not an issue. Not really worth right now while we're building the application. I appreciate your feedback and willingness to test!
