### ISSUE TITLE
Move logfile out of installation directory

### ISSUE THREAD

**Issue by jtljac** [oceancabbage/RimSort#82]
By storing the log file in installation directory, it makes it annoying permission-wise when installing to a standardised place in Linux like `/opt`.

To remove this problem, the log file should be moved to a user directory, like `/home/USER/.local/share/RimSort/` (and I believe the windows equivalent is appdatalocal).

**Comment by twstagg** [comment]
Instead of moving it to user directory, it's now output to tempdir as of b33f08e
