### ISSUE TITLE
Complete "basic mode" UI & related features

### ISSUE THREAD

**Issue by twstagg** [oceancabbage/RimSort#9]
This is the main UI that will be used for RimSort

**Comment by twstagg** [comment]
- Autodetect paths button with proper handling of exceptions

**Comment by twstagg** [comment]
- Need to logically & visually distinguish "local_mods" vs "workshop_mods" in the UI & in the cache
- We can add another key ["localmod"] for each mod to distinguish whether they are:
    - 0 "a workshop mod, NOT a local mod"
    - 1 "a local mod, NOT a workshop mod"
- And use this as a filter to indicate in the UI a mod_list_item 's source for later shenanigans.

**Comment by twstagg** [comment]
- Implement user "community rules db path" preference
    - Will contain a configurable path to the new `customRules.json` file that will contain user defined custom sort rules from a UI element that will need implementing
-  Default to user preference path to DB mod
-  Secondarily, if the user preference was not there or null, check RimPy DB if available (otherwise it would pop up and say "no community rules db found" or something like that)

**Comment by twstagg** [comment]
- Implement a `global_settings_panel` which should coorespond to additional feeds in `settings.json`
    - This is for configuration of things such as `customRules.json` path
    - Include stub option to configure default "mode" (basic, or advanced) for #7 and the aforementioned "splash screen"

**Comment by oceancabbage** [comment]
With the initial mods info panel functionality now merged, tracking two additional minor improvements to this:

1. Support for parsing formatting tags in the description scroll area (e.g. `[h1]` tags are translated to heading font)
2. Properly switching to new mod when traversing mod list with arrow keys

**Comment by twstagg** [comment]
- We need a refresh button! :D

**Comment by oceancabbage** [comment]
Adding/restating things we need to implement to get towards initial release:
- [ ] Warnings and Errors Bar: Situated below active mod list, e.g. 3 warnings(s) 1 error(s)
- [ ] Mod Item Widgets = Icons for core mods, local mods, and workshop mods
- [ ] Mod list scroll bar needs to be consistently styled for all platforms (on windows it looks awful)
- [ ] Run button functionality
- [ ] Autodetect button functionality
- [ ] Refresh button to accommodate setting paths
- [ ] Search bar for mod lists
- [ ] Support for custom rules (come up with your own schema), pulls directly from file in RimSort

**Comment by twstagg** [comment]
Looks completed to me!
